name: Databricks Bundle Validation

on:
  push:
    branches:
      - '**' # Trigger on push to any branch

jobs:
  validate-databricks-bundles:
    name: Run Databricks Bundle Validation
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Databricks CLI
      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      # Step 3: Validate Databricks Bundles
      - name: Validate Databricks Asset Bundles
        run: |
          databricks bundle validate
