name: Validate/ Unittest

on:
  push:
    branches:
      - '**' # Trigger on push to any branch

jobs:
  run-file:
    name: Run Specific File
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Python (if needed, adjust the environment based on your file requirements)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Run the specific file
      - name: Execute Specific File
        run: |
          python path/to/your_file.py
